### ISSUE TITLE
Using the default ports when running a docker run command

### ISSUE THREAD

**Issue by moturi12** [clouder-community/clouder#12]
Hi Yannick,

I had a issue running a container and when the looked at the log , if the server port mapping are not provided it is sending a "False" notation to the docker run command as shown below :
---------------
sudo docker run -d -p False:5000 -p False:443 -p False:22 -v /opt/keys/www-registry_www.server.com:/opt/keys --name www-registry img_registry:1.20150430.091512
stdout : 
stderr : time="2015-05-04T22:10:36-04:00" level="fatal" msg="Invalid hostPort: False" 

-------------------

I think if the server port mapping are not provided, it should use the default docker image ports or if they need to explicitly defined , probably good idea to have this mandatory when creating a container record.

Cheers,
Naran

**Comment by YannickB** [comment]
That's strange, normally if you don't specify a port one shall be autoassigned. Did you specified a start and end port in the server configuration, https://doc.goclouder.net/en/latest/connect-server.html ? Maybe because of this the port stayed to False.

If yes, let the issue open I shall add a warning message in such cases.

**Comment by YannickB** [comment]
I added the message, you can close the issue if this resolve your problem.

**Comment by moturi12** [comment]
Hi Yannick - I haven't defined the ports at server level, I thought adding the ports at server is to open range of ports for all the dockers.


I have added the port mapping in container and is fine.


Cheers,

Naran

Sent from Yahoo7 Mail on Android
