### ISSUE TITLE
Inconsistent Licensing

### ISSUE THREAD

**Issue by lasley** [clouder-community/clouder#141]
Looking through the modules, I am noticing some inconsistent licensing:

* Most manifest files state `Other OSI approved licence`
* Most header files state `LGPL-3`

Note that any module containing an AGPL-3 module in its inheritance chain (`connector` or something dependent on `connector` listed in the `depends` key) is proliferated by that license, and must be subsequently licensed under AGPL-3.

I was going to just make a PR changing everything to AGPL-3, but I noticed that the templates don't actually inherit, so can be licensed under whatever you want. I figured an issue would be best - please let me know if you have any questions on licenses.

**Comment by YannickB** [comment]
Yeah we discussed this during Odoo Experience, I failed to see the inheritance problem when I developped the asynchronous feature.

It's my wish to keep the licence as LGPL-3 (I just don't want to argue with people who will want to make closed-source template for Clouder, this kind of discussion bore me)

According to me, we need to move the asynchronous feature from clouder to a clouder_asynchronous module, and this module shall inherit connector. I don't think it'll be too much difficult.

Also template inherit clouder which inherit connector so according to me AGPL is enforced everywhere, yes we need to do something. In manifest Other OSI approved licence is used because LGPL is not a valid option in Odoo 8.

**Comment by lasley** [comment]
Agreed on the need for non-AGPL in the templates. Those are likely to be very proprietary & there isn't a way to alter them without creating code and inheriting - which then proliferates the module. The last thing we want is a user of our clouder deployment product having to give up their proprietary deployments to all their customers.

Assuming we can break the inheritance chain, the templates would honestly be nice under MIT in order to not force licensing on user modules at all. Just a thought, again boring discussion so I'm good with LGPL too. 

Just in case you're not so versed on licensing, this is an amazing site for comparing - http://choosealicense.com/licenses/

You're correct about the template => clouder => connector inheritance causing AGPL proliferation. We definitely should do something about that.

The need to move the templates out of the licensing umbrella also opens up the possibility for a new discussion - IMO the templates are data files for the most part, it would be nice if we were able to move them out of the code entirely. Possibly even create a `clouder-templates` repo for them in order for pure isolation. Just a thought, I'm still getting versed on the innerworkings here so it could be entirely wrong thought.

**Comment by YannickB** [comment]
#143

**Comment by YannickB** [comment]
Most of the licence issues should be fixed now. Also good news, Odoo 8 accept LGPL-3 now in the manifest so I was able to change the licence everywhere in the manifest.

Regarding the MIT suggestion, I suggest to stick with LGPL because copyleft is only enforced if you change the template itself and if they are doing this for proprietary purpose this is not good practice anyway (you want to inherit it). We'll see if the need arise one day.

Regarding moving the templates out of the main repo, it does not depend if the template is only data or not, most template will always contains .py files because most system commands are issue here (that said, most of them may be moved in salt if they can't be in Dockerfile, it should be the final goal).

Note that some part of Clouder is already out of the main repo : https://github.com/clouder-images. This is needed for Docker Hub images configuration.
We have three possibles strategies : 
-Keep all templates in the main repo like now. We may still have an external repo for extra template not often used.
-Move all templates in another repo. But same problem, it would be best to have some extra template moved out of the repo which contain the main templates.
-Having one repo per template like clouder-images, which I think is the more pythonic but it'd be impossible for them to be under the main OCA repo (same problem than clouder-images, we will never be able to move them under the OCA repo, that doesn't prevent them to be under OCA umbrella).

According to me we should stick to 1st solution for now, and move to 3rd the day we finally have one repo per module in Odoo/OCA.

**Comment by lasley** [comment]
TBH I like your option 3 from the start. Maybe create a `clouder-templates` org, then if/when it comes time for OCA to take over we can just add the script management to them.

I feel like the templates and the application will be evolving at different paces, as they are somewhat independent from each other in terms of what they do. Seems while we're incubating things & creating breaking changes, it would be a good time to handle everything. You know the history in architecture here significantly better than me though, so maybe I'm wrong.

I'm going to talk with some of the OCA board as well, maybe they have some perspective to add. Granularity and small repos are at the core of our values, so there may be some sort of strategy for this already.

**Comment by YannickB** [comment]
Ok, that said the subject of having one module per repo is old topic in the OCA, I don't think they have a solution yet. I'd suggest to stick in 1 for now otherwise we may face problems that other people didn't have until now.

**Comment by lasley** [comment]
This was fixed, closing. Thanks @YannickB
