### ISSUE TITLE
Error: postgresql userName doesn't support caps letter

### ISSUE THREAD

**Issue by microcom** [clouder-community/clouder#27]
Since postgresql username can't contain Caps letter and the username used with a odoo container is based of the service name, you need to set it to lower case in the config file.

**Comment by YannickB** [comment]
I agree, lower case shall be forced for important fields like container/service/base name.

If you don't mind, I'd appreciate a PR on the subject. For example regarding the container name validation, you have to update the regular expression here : https://github.com/clouder-community/clouder/blob/8.0/clouder/clouder_container.py#L138

Sorry for asking for the PR, but I want to encourage people to make PR even for this kind of little modification, otherwise since I have very little time I'll not be able to make it.
Please note there is an ongoing discussion on the mailinglist regarding the legal aspect of the project, I want to make sure everyone is comfortable with the CLA and invite you to join the mailinglist if you don't subscribed already.

**Comment by YannickB** [comment]
Closing all old tickets.
