### ISSUE TITLE
Error: Shinken img

### ISSUE THREAD

**Issue by MarcEtienneDery** [clouder-community/clouder#28]
The supervisord script doesn't run the right executable for shinken. The shinken executable is located at /usr/local/shinken/bin/init.d/shinken

**Comment by YannickB** [comment]
Hello,

If I used directly /etc/init.d/ that's probably because I had trouble with supervisor. If you don't mind, please try with /usr/local/shinken/bin/init.d/shinken and make PR if you managed to make it works.

I also had some trouble with the bind container, because the /etc/init.d/bind reload is not working, so I have to restart the bind container each time I create a base.

Sorry for asking for the PR, but I want to encourage people to make PR otherwise since I have very little time I'll not be able to make it.
Please note there is an ongoing discussion on the mailinglist regarding the legal aspect of the project, I want to make sure everyone is comfortable with the CLA and invite you to join the mailinglist if you don't subscribed already.
