### ISSUE TITLE
Improvement: purge image

### ISSUE THREAD

**Issue by MarcEtienneDery** [clouder-community/clouder#29]
https://github.com/clouder-community/clouder/blob/8.0/clouder/clouder_image.py#L282 
You could use the docker registry api, http://docs.docker.com/registry/spec/api/#deleting-an-image

**Comment by YannickB** [comment]
Well that's new, so they finally released the V2 of the registry and we can now delete an image, that's good news.

Note that I have another problem with the registry : Currently it have to be on the same server that where we want to deploy a container, that's a serious limitation and I need help to resolve this point.

Regarding theses two features please make PR, I want to encourage people to make PR otherwise since I have very little time I'll not be able to make it.
Please note there is an ongoing discussion on the mailinglist regarding the legal aspect of the project, I want to make sure everyone is comfortable with the CLA and invite you to join the mailinglist if you don't subscribed already.
