### ISSUE TITLE
Lots of modules no explainations

### ISSUE THREAD

**Issue by akram1** [clouder-community/clouder#3]
Can you please explain what and how your modules do in details? Module descriptions repeat module names only.

**Comment by YannickB** [comment]
Yes of course but it's a little early for building the documentation since I'm just finishing the dev. Of course it'll be the next priority.

In short, clouder is the main module, it create all the new object/view/security in Odoo to use it to manage your hosting infrastructure.
Then you have one module for each software or component you want to host (like postgres, shinken, odoo etc...) which each contain the data needed and the code specific to the software.

**Comment by YannickB** [comment]
The refactoring is finished and I added a little readme. Functionnal documentation shall be done within two weeks.

Until this moment, even if the website is not finished you can subscribe to the mailing-list https://www.goclouder.net/groups if you have other questions.

I'll close the issue when the functionnal documentation is done.

**Comment by YannickB** [comment]
Hello,

The functional documentation is available at https://doc.goclouder.net/en/latest/, so I close the issue.
