### ISSUE TITLE
Vision for distributedOS

### ISSUE THREAD

**Issue by pierreozoux** [clouder-community/clouder#6]
To continue the discussion we have at IndieHosters, and with your great inputs, I'd like to know your vision for the future of clouder.

Most modern PaaS provide API (https://github.com/weihanwang/docker-ecosystem-survey#orchestration-frameworks-ie-paas-software-for-docker, yours is down the list with IndiePaaS :) )

Why do you want to build yet another PaaS, and not use one that is already developed (like mesos for instance?)

This question really bother me personally, I have troubles to answer it myself, and I'm wondering if you have an answer :)

Because, you could imagine simply developping an Odoo plugin to interface with paz.sh or mesos, and it would be done, right?

Just wondering!

Thanks!

**Comment by YannickB** [comment]
Yeah of course that's the eternal question of "Yet another free software which does the exact same thing and divide the efforts", which is always raised until one software make everybody happy (And I hope Clouder will be the one).
I'm the first to complain about this tendency in the free software world, and I thought a lot before starting to do the same thing with Clouder. And the conclusion was : nothing already exist which does what Clouder does (or I didn't found it in time).

A bit of history : 
The current Clouder is the fifth complete refactoring of the scripts I used to host the projects I was working on. The first was a very ugly, monolithic, shell script which managed Drupal instances for my Wikicompare project (demo.wikicompare.info). After this I started working for an ERP for communities project with an association, and so I started to need to host Odoo instances.
Managing both Drupal and Odoo instances, which are not at all based on the same techno, made me though a lot of what was the best way to host them, and after many refactoring I ended up moving my scripts on Odoo, using Docker, and found a design which allow me to use my scripts for hosting any application. 
So at first it wasn't at all a project I were planning to promote, it was just for my own needs because nothing on the market was simple enough to use. And when I finished, I realized I made it the right way (because I needed it myself), and this is the moment I started to promote it.

What I want is anybody with just a little bit of technical knowledge (like an adminsys in company or just some dudes for their friends) shall be able to do the following : 
-Access to an orchestrator instance (whether they install it of get it from a provider like me)
-Connect their server to the orchestrator
-They only have to play with the graphical interface to install the applications they want
-And very important, it shall be flexible enough to be used for professional hosting. This is the real challenge, you shall be able to use the exact same techno if you want to deploy a Mumble for talking with your friend while playing video games, or if you want to use Clouder to deploy the infrastructure of a 5000+ company, including their webshop.

Currently, I defy you to find a software which can do this exact process. Yes you can use orchestration software for a company, but it'll never be easy enough to use for the 18year old dude which want to install some software on his server for his friends.
The reason is : All current orchestrator have no good graphical interface. You can't add custom fields, nor menu etc... And this is were Odoo shine, you can add your own fields, integrate your data with the other business modules, and either you use the backoffice to have quickly a ready to use interface, or the CMS to build a state of the art user experience.

For all theses reasons, Clouder is the place where you want to store your user credentials, the list of applications you want to deploy, the list of containers, the links between them etc... And this is Clouder which launch the event when something happen on his interface (new form, click on button etc...)

But don't mistake me, that's the only goal of Clouder, to be the place where data are stored and managed. To me, it's completely ok that after you create your container in Clouder, that Clouder connect to a Mesos container which will managed the other containers. 
I don't want to reinvent the wheel, I want to use all the existing softwares as components so Clouder only have to store the data and launch the minimum of system command required.
As long as the admin only have to play with the graphical interface to manage his apps, it's compatible with the Clouder philosophy.

**Comment by pierreozoux** [comment]
This is great what you want to build, and I'm sure we'll find many ways to collaborate with indiehosters.
And at the end, we even might end up with the same infra.

With @michielbdejong , we also want to build something very similar. Gives the tools for anybody to become an IndieHosters, just by putting an amazon API key in some web interface we provide.
At the end of the day, it could be a web interface that provision a clouder instance for this person.

I think all this ecosystem is growing, and we'll soon have tools to do it the right way.

I close this issue, as it is more about philosophy :)

Thanks again and looking forward for the [OuiShareLabs](http://camp.ouisharelabs.net/2015/) :)
