### ISSUE TITLE
Additional application for Сlouder

### ISSUE THREAD

**Issue by collex100** [clouder-community/clouder#65]
There is an idea, if you find it is not on the current topic, please tell me. I found that the model works Clouder can operate as a Configuration Management. Managing such an application as Ansible. Requires three functions that perform Clouder: 
1.Connecting to the server via SSH. 
2.Execution playbook. 
3.And perform log collection. 
There are three basic document. What do you think about this @YannickB?

**Comment by YannickB** [comment]
Well as a reminder I first developed Clouder for my own need, while not being an expert with hosting. That way at least I am sure to be able to manage all concepts that I need ("they did it because they didn't knew it was impossible"), even if I may try to integrate other softwares as sublayer later if they are doing the job to avoid as much as possible reinventing the wheel (cf the discussion about the PaaS layer, here I hope to avoid manage PaaS concepts like for example private network between containers).

This means that each time someone quote a software, I go check to see if I reinvented the wheel... Well I have to say, it seems I underestimated Ansible, it looks indeed really close to Clouder, especially that's the first time I see the argument "multi-tiers deployment", if this means it manage links between applications, like I do with Clouder, then we are in direct competition. The web interface, Ansible Tower, seems to be closed source through.

To answer your question, yes Clouder is a web interface which connect to your server with ssh, deploy your containers, execute configuration (not with playbook but with system command defined in python code), and all executed command are logged, so we can can consider it a Configuration Management system.

The underlying question according to me is should we use Ansible as a sublayer, and make Clouder a direct competitor of Ansible Tower... I don't know yet, I only threw a quick look on their website, I need to investigate, feedback are welcomed. The crucial question is : are playbook as flexible as system commands in python code?

As always I remind the goal of Clouder : A tool to deploy complex and state of the art infrastructure for your enterprise/association/hosting company even if your are a novice sysadmin, you just click on buttons and you get your whole infra in an hour.You don't have to make days of research about docker, ansible, shinken, the applications you want to host etc... If a template exist, you just get it deployed and then you look at the details of your infrastructure only when you need it.

**Comment by collex100** [comment]
Ansible is opensource and Ansible Tower is commerce product. Ansible is CLI and not have web. If it is possible to control Ansible from the Odoo it is direct competition for the Ansible Tower (If certainly add  functions of monitoring and analysis.). 

Ansible is written in Python. Playbook is similar in meaning to Doсkerfile (As well as https://galaxy.ansible.com/ is similar https://hub.docker.com/). Ansible uses the YAML file format and uses the Jinja2 templating languages.
http://www.allitebooks.com/?s=Ansible (Ansible: Up and Running) - You can read the first page to have fully understood how it works.

Ansible is an IT automation tool. It is said that Ansible is so simple that anyone can study the it in one night. 

Ansible, Rancher, Openshift - Is what better? Hard to say.

**Comment by collex100** [comment]
If anyone is interested, you can look at the situation as:
http://stackshare.io/ansible#more
http://stackshare.io/rancher#more
http://stackshare.io/openshift#more

**Comment by pasgou** [comment]
Could I complete ?
I just discover Clouder which seems to me a great solution to deploy my own projects when I will be familiarized with it.
I m not a SysAdmin, only a kind of part time geek.

And I discovered Ansible in some 'Linux Pratique' or 'Linux Magazine' .

I think it could be complementary : Ansible to deploy the servers (install dependencies) which will receive containers from Clouder. It could make possible to deploy new server without any direct work on it.

**Comment by YannickB** [comment]
Even me I'm not sure how is the best way to implement an integration with ansible, and maybe it's too soon too. I think there is potential, we'll need a proof of concept to go further I think.

**Comment by YannickB** [comment]
#119 The discussion will continue here I think, we are seriously considering using a tool between Clouder and containers. Closing
