### ISSUE TITLE
[8.0] Feature request: clouder_template_open_xchange

### ISSUE THREAD

**Issue by lukebranch** [clouder-community/clouder#8]
@YannickB ,

I would like to request a new template module for Clouder for Open-Xchange:

http://www.open-xchange.com/

It is by far the best open-source webmail interface i've seen and the features allow for Microsoft Exchange style features. I use it because I can add multiple email addresses to a single webmail login among many other things, but I think it would be ideal for the clouder project.

I'll be creating an install script for this on Ubuntu 14.04 soon, and would be happy to submit a link if you like.

**Comment by YannickB** [comment]
Thanks for the suggestion, I agree it looks like a good webmail and I know we'll need mail in Clouder as soon as we can.

Please note that since I am currently spending all my time for the communication around the project, someone else will have to make the template module. You may consider making the template module yourself, otherwise we'll let this issue open until somebody take care of it.

Again, thank you for the suggestion.

**Comment by lukebranch** [comment]
@YannickB ,

Thanks for letting me know. I will take a look at how the template modules are built and look into building one myself in the near future. If I was to submit a PR to this project are there any kinds of automated tests that I should do beforehand (like the OCA/Runbot tests) to make sure everything is compliant with your standards/requirements for the project?

I'll close this, and the other issue for now until I have time to work on a template module.

**Comment by YannickB** [comment]
The automated tests are a concern with Clouder, it's very difficult to create them because we'll need to have a test server where the automated test will connect to test the installations.

Since we have no time to set such complex infrastructure now, I don't think we'll have automated tests before a long time.

I reopen the issue, I find open-xchange really interesting and I want people who pass here to see this suggestion, in case some have time to help to make the template module. Again, thanks for this.

**Comment by YannickB** [comment]
Closing all old tickets
