### ISSUE TITLE
Multi odoo install

### ISSUE THREAD

**Issue by yazzou** [clouder-community/clouder#9]
Hello
I am looking for a solution that would help me set up multiple independent instances of ODOO, each instance will be accessible on a domain or subdomain hosted on this server. I do not have very advanced skills at administrating a server and would like to know before diggin into you documentation if it the purpose of what you are proposing. 
Thanks for your time
Yaz

**Comment by YannickB** [comment]
Hello,

Yes this is exactly the purpose of Clouder. Note that this is still in beta so there may be still not enough security and control for a beginner but it will allow you to setup a professionnal hosting, don't hesitate to ask on the mailing list if you need help.

**Comment by yazzou** [comment]
Ok Great ! I ll give it a try i just rented a Kimsuffi server . It is the KS-2	Atom™ N2800 listed here https://www.kimsufi.com/fr/index.xml. i ll install Debian on it. But for not having surprises after i would like to know if is there ideal partionning for the disk to be recommended to allow all instances work. 
Merci !

**Comment by YannickB** [comment]
Hello, I have no recommendation regarding the partitioning.  Note that the docker instances will be stored in /var and the applications archives in /opt.

It's best you not loose too much time installing the Odoo instance which will pilot your infrastructure, do you want me to create one for you ?

**Comment by yazzou** [comment]
Hello
You mean you would create an instance for me on your server to allow
creating other instances on main domains ? I was expecting to make the full
install on the kimsufi but i d be happy to test it before

2015-04-27 10:01 GMT+02:00 Yannick Buron <notifications@github.com>:

> Hello, I have no recommendation regarding the partitioning. Note that the
> docker instances will be stored in /var and the applications archives in
> /opt.
>
> It's best you not loose too much time installing the Odoo instance which
> will pilot your infrastructure, do you want me to create one for you ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clouder-community/clouder/issues/9#issuecomment-96545764>
> .
>



-- 
http://www.mediaterranee.com

**Comment by YannickB** [comment]
One obvious limitation of Clouder is the fact that you can't use Clouder to manage the container where is installed this same Clouder. It would create a loop which will make it really difficult to maintain.

You can decide to install your Clouder on the host server, but in this case you'll have no supervision/backup/postfix etc... linked to it unless you configure them manually. That's why I think we need to have the Clouder instances from another server.

So to ease the adoption of Clouder, I propose for those who ask it to host one instance for them. Probably in the future, I guess it'll be the core of my business model but for now it's free. Of course, I encourage you to also host Clouder instances for others.

**Comment by YannickB** [comment]
Please send me you address mail if you want me to create your instance. For those who read this and want one too, don't hesitate to tell me.

**Comment by YannickB** [comment]
I guess we can now close this ticket.
